os: Visual Studio 2017

# version format
version: 3.0.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

build_script:
  - cd BuildPackage
  - Build.bat

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/slimsy/
    symbol_server: https://www.myget.org/F/slimsy/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: v1

    # MyGet Deployment for builds & releases from feature branches
#  - provider: NuGet
#    server: https://www.myget.org/F/slimsy/
#    symbol_server: https://nuget.symbolsource.org/MyGet/slimsy
#    api_key:
#      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
#    artifact: /.*\.nupkg/
#    on:
#      branch: /feature\/.*/

    # MyGet Deployment for builds & releases from srcsetsupport (v2) branch
  - provider: NuGet
    server: https://www.myget.org/F/slimsy-v2/
    symbol_server: https://www.myget.org/F/slimsy-v2/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop

  # MyGet Deployment for builds & releases v3 branch
  - provider: NuGet
    server: https://www.myget.org/F/slimsy-v2/
    symbol_server: https://www.myget.org/F/slimsy-v2/symbols/api/v2/package
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: temp-umb-v8

     # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: c0LwOGqoFZIieyy8CHrUtYQOD0HL0rG5tV2DS+8FHv34BKs/LSGGtmWWep5O7GbV
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

     # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: adk3pI9HCByZg2VRxplX9UR6qHf97bA3as6dusxLswCKI8BQQE8DO5a0frLrI+EO
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true